"""Add gamemodes table

Revision ID: 4f6f265aa5d2
Revises: 357a5d00e494
Create Date: 2025-03-29 16:22:39.315298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6f265aa5d2'
down_revision = '357a5d00e494'
branch_labels = None
depends_on = None


def upgrade():
    # First check if game_modes table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'game_modes' not in inspector.get_table_names():
        # Create table only if it doesn't exist
        op.create_table('game_modes',
            sa.Column('gamemode_id', sa.BigInteger(), nullable=False),
            sa.Column('gamemode_name', sa.String(), nullable=False),
            sa.PrimaryKeyConstraint('gamemode_id'),
            sa.UniqueConstraint('gamemode_id'),
            sa.UniqueConstraint('gamemode_name')
        )

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['country_id'])

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'game_modes', ['gamemode_id'], ['gamemode_id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('game_modes')
    # ### end Alembic commands ###
