"""Add flag names table

Revision ID: b0fe7d2ac32b
Revises: 7a33180d3e2c
Create Date: 2025-04-07 13:54:53.948849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fe7d2ac32b'
down_revision = '7a33180d3e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flag_names', schema=None) as batch_op:
        batch_op.alter_column('code2l',
               existing_type=sa.VARCHAR(length=2),
               comment=None,
               existing_comment='ISO 2-letter code',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Language code (ie. pt-pt)',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.drop_index('idx_17238_fk_country_name_country_idx')
        batch_op.drop_index('idx_17238_unique_code2l_language')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['login_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('flag_names', schema=None) as batch_op:
        batch_op.create_index('idx_17238_unique_code2l_language', ['code2l', 'language'], unique=True)
        batch_op.create_index('idx_17238_fk_country_name_country_idx', ['country_id'], unique=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=5),
               comment='Language code (ie. pt-pt)',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('code2l',
               existing_type=sa.VARCHAR(length=2),
               comment='ISO 2-letter code',
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###
