"""Rename score table field

Revision ID: b4a4b102a6dc
Revises: b744c2b8113c
Create Date: 2025-03-24 15:01:31.747715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a4b102a6dc'
down_revision = 'b744c2b8113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'id', new_column_name='score_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'score_id', new_column_name='id')
    # ### end Alembic commands ###
